# NumPy Tutorial

In [1]:
import numpy as np

In [2]:

myarr = np.array([[2,3,4,5]],np.int64)

In [3]:

myarr[0,1] = 45

In [4]:
myarr.shape

(1, 4)

In [5]:
myarr.dtype

dtype('int64')

In [6]:
myarr

array([[ 2, 45,  4,  5]], dtype=int64)

# Array Creation :Conversion from other Python structures (e.g., lists, tuples)

In [7]:
listarry = np.array([[1,2,4],[4,4,5],[5,3,7]])

In [8]:
listarry

array([[1, 2, 4],
       [4, 4, 5],
       [5, 3, 7]])

In [9]:
listarry.shape

(3, 3)

In [10]:
listarry.dtype

dtype('int32')

In [11]:
listarry.size

9

In [12]:
np.array({1,2,3})

array({1, 2, 3}, dtype=object)

In [13]:
np.array({23,34,34})

array({34, 23}, dtype=object)

# Intrinsic numpy array creation objects (e.g., arange, ones, zeros, etc.)

In [14]:
np.zeros((1,5))

array([[0., 0., 0., 0., 0.]])

In [15]:
zero = np.zeros((5,5))

In [16]:
zero

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
rng = np.arange(15)

In [18]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [19]:
rng1 = np.arange(1,10)

In [20]:
rng1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
rng2 = np.arange(1,11)

In [22]:
rng2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
lspace = np.linspace(1,8,5)

In [24]:
lspace

array([1.  , 2.75, 4.5 , 6.25, 8.  ])

In [25]:
for i in lspace:
    print(i)

1.0
2.75
4.5
6.25
8.0


In [26]:
n = len(lspace)

for i in range(n):
    print('index' , i , '=' ,lspace[i])

index 0 = 1.0
index 1 = 2.75
index 2 = 4.5
index 3 = 6.25
index 4 = 8.0


In [27]:
emp = np.empty((4,6))

In [28]:
emp

array([[6.23042070e-307, 1.86918699e-306, 1.69121096e-306,
        1.33511290e-306, 6.23058368e-307, 8.90105597e-307],
       [6.23053614e-307, 7.56592338e-307, 1.60220528e-306,
        7.56602523e-307, 1.42417221e-306, 1.37961641e-306],
       [2.22522597e-306, 1.33511969e-306, 1.24610383e-306,
        1.69118108e-306, 8.06632139e-308, 1.20160711e-306],
       [1.69119330e-306, 1.29062229e-306, 1.29060531e-306,
        2.13620807e-306, 1.69118787e-306, 2.56765117e-312]])

In [29]:
emp_like = np.empty_like(lspace)

In [30]:
emp_like

array([1.  , 2.75, 4.5 , 6.25, 8.  ])

In [31]:
emp_like.size

5

In [32]:
emp_like.dtype

dtype('float64')

In [33]:
emp_like.shape

(5,)

In [34]:
ide = np.identity(45)

In [35]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [36]:
ide.shape 

(45, 45)

In [37]:
arr = np.arange(99)

In [38]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [48]:
arr =arr.reshape(3,33)

In [49]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [54]:
arr = arr.ravel()


In [55]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [56]:
arr.shape

(99,)

In [59]:
x =[[1,2,3],[4,5,6],[7,1,0]]

In [60]:
x

[[1, 2, 3], [4, 5, 6], [7, 1, 0]]

In [61]:
ar = np.array(x)

In [62]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [65]:
ar.sum(axis = 0)

array([12,  8,  9])

In [66]:
ar.sum(axis = 1)

array([ 6, 15,  8])

In [67]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [69]:
ar.flat

In [73]:
for item in ar.flat:
    print(item)
    

1
2
3
4
5
6
7
1
0


** no of array dimensio **

In [75]:
ar.ndim

2

In [76]:
ar.size

9

In [77]:
ar.nbytes

36

In [78]:
one = np.array([1,33,4,45,34,23,23])

In [79]:
one

array([ 1, 33,  4, 45, 34, 23, 23])

In [80]:
one.argmax()

3

In [81]:
one.argmin( )

0

In [82]:
one.argsort()

array([0, 2, 5, 6, 1, 4, 3], dtype=int64)

In [83]:
ar.argmin()

8

In [84]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [85]:
ar.argmax()

6

In [86]:
ar.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [89]:
ar.argmax(axis=1)

array([2, 2, 0], dtype=int64)

In [90]:
ar.argmin(axis=0)

array([0, 2, 2], dtype=int64)

In [93]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [94]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [95]:
ar.reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

In [96]:
ar.reshape((1,9))

array([[1, 2, 3, 4, 5, 6, 7, 1, 0]])

In [97]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [101]:
ar.reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [102]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [103]:
ar1 = np.array([[1, 3, 2],
       [4, 8, 6],
       [3, 1, 0]])

In [104]:
ar1

array([[1, 3, 2],
       [4, 8, 6],
       [3, 1, 0]])

In [105]:
ar + ar1

array([[ 2,  5,  5],
       [ 8, 13, 12],
       [10,  2,  0]])

In [106]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [107]:
ar1

array([[1, 3, 2],
       [4, 8, 6],
       [3, 1, 0]])

In [108]:
ar+ar1

array([[ 2,  5,  5],
       [ 8, 13, 12],
       [10,  2,  0]])

In [109]:
ar * ar1

array([[ 1,  6,  6],
       [16, 40, 36],
       [21,  1,  0]])

In [110]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [111]:
ar.max()

7

In [112]:
ar1.min()

0

In [113]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [116]:
type(np.where(ar>4))

tuple

In [117]:
import sys

In [118]:
py_ar = [1,23,4,5]

In [119]:
num_ar = np.array(py_ar)

In [120]:
sys.getsizeof(1) * len(py_ar)

112

In [121]:
num_ar.itemsize*num_ar.size

16